== Promisesの書き方

Promiseの基本的な書き方について解説します。

=== promiseオブジェクトの作成

promiseオブジェクトを作る流れは以下のようになっています。

. `new Promise(fn)` の返り値がpromiseオブジェクト
. 引数となる関数fnには `resolve` と `reject` が渡る
. `fn`には非同期等の何らかの処理を書く
    * 処理結果が正常なら、`resolve(結果の値)` を呼ぶ
    * 処理結果がエラーなら、`reject(Errorオブジェクト)` を呼ぶ

実際にXHRでGETをするものをpromiseオブジェクトにしてみましょう。

[[getURL]]
[source,js]
----
include::embed/embed-xhr-promise.js[]
----

XHRで200で値が取得できた場合のみ `resolve` として、
それ以外はエラーであるとして `reject` しています。

`resolve(req.response)` ではレスポンスの内容を引数に入れています。
resolveの引数に入れる値には特に決まりはありませんが、コールバックと同様に次の処理へ渡したい値を入れるといいでしょう。
(この値は`then`メソッドで受け取ることが出来ます)

Node.jsをやっている人は、コールバックを書く時に `callback(error, response)` と第一引数にエラーオブジェクトを
入れることがよくあると思いますが、Promisesでは役割がresolve/rejectで分担されているので、
resolveにはresponseの値のみをいれるだけで問題ありません。


次に、`reject` の方を見て行きましょう。

XHRで`onerror`のイベントが呼ばれた場合はもちろんエラーなので`reject`を呼びます。
ここで`reject`に渡している値に注目してみてください。

エラーの場合は `reject(new Error(req.statusText));` というようにErrorオブジェクトとして渡している事がわかると思います。
`reject` には値であれば何でも良いのですが、一般的にErrorオブジェクト(またはErrorオブジェクトを継承したもの)を渡すことになっています。

`reject` に渡す値はrejectする理由を書いたErrorオブジェクトとなっています。
今回は、ステータスコードが200以外であるならrejectするとしていたため、`reject`にはstatusTextを渡しています。
(この値は`then`メソッドの第二引数 or `catch` メソッドで受け取ることが出来ます)

=== promiseオブジェクトに処理を書く

先ほどの作成したpromiseオブジェクトを返す関数を実際に使ってみましょう

[source,js]
getURL("http://example.com/"); // => promiseオブジェクト

<<promises-overview>> でも簡単に紹介したようにpromiseオブジェクトは幾つかインスタンスを持っており、
これを使いpromiseオブジェクトの状態に応じて一度だけ呼ばれるコールバックとなる関数を登録します。

promiseオブジェクトに登録する処理は以下の2種類が主となります

* promiseオブジェクトが **resolve** された時の処理(onFulfilled)
* promiseオブジェクトが **reject** された時の処理(onRejected)

[[promise-value-flow]]
.promise value flow
image::img/promise-onFulfilled_onRejected.png[promise-resolve-flow]

まずは、`getURL`で通信が成功して値が取得出来た場合の処理を書いてみましょう。

[NOTE]
この場合の _通信が成功した_ というのは _promiseオブジェクトがresolveされた_ 時という事

**resolve**された時の処理は、 <<promise.then,`.then`>> メソッドに処理をする関数を渡すことで行えます。

[source,js]
----
var URL = "http://localhost:3000/?status=200&body=text";
getURL(URL).then(function onFulfilled(value){ // <1>
    console.log(value);
});
----
<1> 説明しやすくするためコールバック関数に `onFulfilled` という名前を付けています

<<getURL,getURL関数>> 内で `resolve(req.response);` によってpromiseオブジェクトが解決されると、
値と共に`onFulfilled` 関数が呼ばれます。

このままでは通信エラーが起きた場合などに何も処理がされないため、
今度は、`getURL` で何らかの問題があってエラーが起きた場合の処理を書いてみましょう。

[NOTE]
この場合の _エラーが起きた_ というのは _promiseオブジェクトがrejectされた_ 時という事

**reject**された時の処理は、<<promise.then,`.then`の第二引数>> または <<promise.catch,`.catch`>> メソッドに処理をする関数を渡す事で行えます。

先ほどのソースに

[source,js]
----
var URL = "http://localhost:3000/?status=500";
getURL(URL).then(function onFulfilled(value){
    console.log(value);
}).catch(function onRejected(error){ // <1>
    console.log(error);
});
----
<1> 説明しやすくするためエラーが起きた時に呼ばれる関数に `onRejected` という名前を付けています

promiseオブジェクトが何らかの理由で例外が起きた時、または明示的にrejectされた場合に、
その理由(Errorオブジェクト)と共に <<promise.catch,`.catch`>> の処理が呼ばれます。

<<promise.catch,`.catch`>>は`promise.then(undefined, onRejected)`のエイリアスであるため、
同様の処理は以下のように書くことも出来ます。

[[catch-as-alias]]
[source,js]
----
getURL(URL).then(onFulfilled, onRejected);// <1>
----
<1> onFulfilled, onRejected それぞれは先ほどと同じ関数

基本的には、<<promise.catch,`.catch`>>を使いresolveとrejectそれぞれを別々に処理した方がよいと考えらますが、
両者の違いについては <<thenとcatchの違い>> で紹介します。

==== まとめ

この章では以下のことについて簡単に紹介しました。

* `new Promise` を使いpromiseオブジェクトの作成
* <<promise.then,`.then`>> や <<promise.catch,`.catch`>> を使ったpromiseオブジェクトの処理

Promisesの基本的な書き方はこれがベースとなり、
他の多くの処理はこれを発展させたり、用意されたStatic Method等を利用したものになります。

ここでは、同様の事はコールバック関数を渡す形でも出来るのに対してPromisesで書くメリットについては触れていませんでしたが、
次の章では、Promiseのメリットであるエラーハンドリングの仕組みをコールバックベースの実装と比較しながら見て行きたいと思います。